// src/client/components/TransactionList.tsx
import React from 'react';

interface TransListProps{
  transList: Array<any>;
}

const TransactionList = (props: TransListProps) => {
  return (
    <div className="transactions">
      <h3>Transactions</h3>
      <table className="transactions-table">
        <thead>
          <tr>
            <th>Date</th>
            <th>Description</th>
            <th>Amount</th>
            <th>Category</th>
          </tr>
        </thead>
        <tbody>
          {props.transList.map(record => (
            <tr className="t-records" key={record.id}>
              <td>{record.date}</td>
              <td>{record.description}</td>
              <td>{record.amount}</td>
            </tr>
          ))}
        </tbody>

      </table>
    </div>
  )
}

export default TransactionList;

// src/client/components/TransactionList.vue
<template>
  <div class="txn">
    <h3>Transactions</h3>
    <div class="txn-table">
      <div class="txn-header txn-row">
        <div class="txn-data">Date</div>
        <div class="txn-data">Description</div>
        <div class="txn-data">Amount</div>
        <div class="txn-data">Category</div>
      </div>
      <div class="txn-row" v-for="record in trans" v-bind:key="record.id">
        <div class="txn-data">{{ record.date }}</div>
        <div class="txn-data">${{ record.amount }} </div>
        <div class="txn-data">{{ record.description }}</div>
        <select class="txn-data">
          <option>None</option>
          <option>A</option>
          <option>B</option>
        </select>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
  export default {
    name: 'TransactionList',
    props: {
      trans: {
        type: Array
      }
    }
  }
</script>
