// src/client/App.tsx
import React from 'react';
// import TransactionList from './components/TransactionList';
// import BugetCategoryList from './components/BugetCategoryList';
// import AddCategory from './components/AddCategory';
import FileUpload from './components/FileUpload';



class App extends React.Component {
  render() {
    return (
      <div>
        <h1>Smart Wallet</h1>
        <FileUpload />
        {/* <div className="app">
          <TransactionList />
        </div>
        <div className="category">
          <h3>Budget Categories</h3>
          <BugetCategoryList />
          <AddCategory />
        </div> */}
      </div>
    )
  }
}

export default App;


// interface Category {
//   budget: string,
//   createdAt: string,
//   id: number,
//   name: string,
//   updatedAt: string,
// }

// interface Record {
//   Category: Category,
//   CategoryId: number,
//   amount: string,
//   createdAt: string,
//   date: string,
//   description: string,
//   id: number,
//   updatedAt: string,
// }

// const trans: Array<Record> = [];
// const categories: Array<Category> = [];

// src/client/App.vue
<template>
  <div>
    <h1>Smart Wallet</h1>
    <div class="app">
     <TransactionList v-bind:trans="trans" v-bind:categories="categories" ></TransactionList>
    </div>
    <div class="category">
      <h3>Budget category</h3>
      <BudgetCategoryList v-bind:categories="categories"></BudgetCategoryList>
    </div>
  </div>
</template>

<script>
  import TransactionList from './components/TransactionList';
  import BudgetCategoryList from './components/BugetCategoryList';
  export default {
    name: 'App',
    components: { TransactionList, BudgetCategoryList },
    props: {
      trans: {
        type: Array
      },
      categories: {
        type: Array
      },
    }
  }
</script>
